name: Run Library Automation

on:
  schedule:
    - cron: '0 * * * *'  # हर 1 घंटे में ऑटोमैटिक रन होगा
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install feedparser google-api-python-client google-auth

      - name: Run script
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
          GCP_CLIENT_SECRET: ${{ secrets.GCP_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python main.py
