name: Generate Blogger XML

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install feedparser

      - name: Run XML Generator
        run: python main.py

      - name: Commit & Push XML Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add blogger_import_*.xml
          git commit -m "Generate 10 small XML files [skip ci]" || exit 0
          git push origin main
