name: Run Premchand Library Script

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # हर 30 मिनट में अपने आप चलेगा

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install feedparser requests google-api-python-client google-auth

      - name: Run script
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GCP_CLIENT_ID: ${{ secrets.GCP_CLIENT_ID }}
          GCP_CLIENT_SECRET: ${{ secrets.GCP_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          python main.py
